### ISSUE TITLE
Accept more options for target inputs and outputs

### ISSUE THREAD

**Issue by fbecart** [fbecart/zinoma#16]
Žinoma currently accepts [an array of input paths](https://github.com/fbecart/zinoma#targetstarget_nameinput_paths) to make a target incremental.

Pragmatically, these inputs could also be:

- environment variables
- outputs of commands
- response body of HTTP requests
- ...

While avoiding making the API too complex, we should make space for more options.

**Comment by fbecart** [comment]
Here is a proposed format:

```yaml
target:
  build_docker:
    inputs:
      - { type: env_var, var_name: DOCKER_VERSION }
      - { type: files, path: . }
    outputs:
      - { type: cmd_stdout, cmd: 'docker image ls todos/backend:latest --format "{{.ID}}"' }
```

**Comment by fbecart** [comment]
Another possibility:

```yaml
target:
  build_docker:
    inputs:
      - env_var: DOCKER_VERSION
      - fs_path: .
    outputs:
      - cmd_stdout: docker image ls todos/backend:latest --format "{{.ID}}"
```
