### ISSUE TITLE
Directory `.zinoma` should be ignored in watchers and incremental builds

### ISSUE THREAD

**Issue by fbecart** [fbecart/zinoma#36]
When the inputs/outputs of a target are not particularly clear to the developer, it is common to use `.` as an input path or output path.

e.g.

```yaml
targets:
    docker_build:
        input_paths: [.]
        build: docker build -t my_docker_image .
```

This issue is that `.zinoma`, which is located in `.`, will systematically invalidate the last build, despite the fact that it is never a source directory, and never contains build targets.

`.zinoma` should be systematically ignored when computing paths hashes, and when watching the directory for changes.
