### ISSUE TITLE
Infer target inputs from dependencies

### ISSUE THREAD

**Issue by fbecart** [fbecart/zinoma#40]
It is currently possible to specify targets dependencies (other targets), inputs, and outputs.

However, it seems that, most of the time, a target has as inputs the outputs of its dependencies. This induces a lot of repetition in the Yaml configuration.

For instance:

https://github.com/fbecart/zinoma-node-example/blob/4412ec4166e8e4c709163353adad0acdfa3aafae/backend/zinoma.yml#L17-L22

https://github.com/fbecart/zinoma-node-example/blob/4412ec4166e8e4c709163353adad0acdfa3aafae/webapp/zinoma.yml#L25-L31

https://github.com/fbecart/zinoma-node-example/blob/4412ec4166e8e4c709163353adad0acdfa3aafae/zinoma.yml#L10-L15

It would be nice to have a way to easily add the outputs of the dependencies as inputs. Doing so entirely automatically probably not be accurate either, as, sometimes, a target depends only on a subset of the resources created by the targets it depends on.

**Comment by fbecart** [comment]
__Design suggestion__

`<target_name>::output` would become a resource set, that can be used as the input for a different target.

Example:

```yaml
targets:
  npm_install:
    input:
      - paths: [package.json, package-lock.json]
    output:
      - paths: [node_modules]
    build: npm install

  npm_test:
    input:
      - npm_install::output
      - paths: [package.json, src, test]
    build: npm run test
```

The `input` `npm_install::output` would be equivalent to having `npm_install` as a dependency + having its output as input.
