### ISSUE TITLE
Daemons as services

### ISSUE THREAD

**Issue by fbecart** [fbecart/zinoma#52]
Žinoma makes it possible to define services and use them as dependencies of other targets. At the moment, a service is specified as a script to run. That script will be killed as Žinoma exits. In watch mode, Žinoma restarts services by killing and starting them again.

Žinoma could also accept services accessible as daemons.

These services can usually be operated by a set of commands (start, stop, and sometimes restart). For instance:

```yaml
targets:
  mongodb:
    service:
      start: sudo systemctl start mongod
      stop: sudo systemctl stop mongod
      restart: sudo systemctl restart mongod
```
